on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
  
        - uses: actions/setup-python@v5
          with:
            python-version: 3.11

        - run: |
            pip install -r requirements.txt

        - run: |
            echo '${{ secrets.ENV }}' > .env

        - run: |
            python main.py
  